#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: docs/examples/import-users.sh <users.csv>

Imports users from a simple CSV file with the columns:
  login,roles

The roles column is a pipe- or semicolon-separated list of role names or role
UUIDs, for example:
  alice,User
  bob,User|Observer
Quoted CSV fields and commas inside field values are not handled.

For each row, the script checks whether the user already exists. Existing users
have their role assignments updated. Missing users are created with a secure
autogenerated password and the generated password is printed with the result.

Environment:
  GVM_GATEWAY_BASE_URL              Default: http://127.0.0.1:8080
  GVM_GATEWAY_USERNAME              Default: admin
  GVM_GATEWAY_PASSWORD              Default: admin
EOF
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

api_get() {
  local path="$1"
  curl -fsS \
    -H "Authorization: Bearer ${SESSION_TOKEN}" \
    "${BASE_URL}${path}"
}

api_post_json() {
  local path="$1"
  local body="$2"
  printf '%s' "${body}" | curl -fsS \
    -H "Authorization: Bearer ${SESSION_TOKEN}" \
    -H 'Content-Type: application/json' \
    -X POST \
    --data-binary @- \
    "${BASE_URL}${path}"
}

api_put_json() {
  local path="$1"
  local body="$2"
  printf '%s' "${body}" | curl -fsS \
    -H "Authorization: Bearer ${SESSION_TOKEN}" \
    -H 'Content-Type: application/json' \
    -X PUT \
    --data-binary @- \
    "${BASE_URL}${path}"
}

create_session() {
  curl -fsS \
    -u "${USERNAME}:${PASSWORD}" \
    -H 'Accept: application/json' \
    -X POST \
    "${BASE_URL}/api/v1/session"
}

delete_session() {
  if [[ -n "${SESSION_TOKEN:-}" ]]; then
    curl -fsS \
      -H "Authorization: Bearer ${SESSION_TOKEN}" \
      -X DELETE \
      "${BASE_URL}/api/v1/session" >/dev/null || true
  fi
}

cleanup() {
  rm -f "${CSV_USERS_FILE:-}"
  rm -rf "${TMP_DIR:-}"
  delete_session
}

parse_csv_users() {
  local csv_file="$1"
  awk -F, -v path="${csv_file}" '
    function trim(value) {
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
      return value
    }

    function fail(message) {
      print message > "/dev/stderr"
      failed = 1
      exit 1
    }

    NR == 1 {
      for (i = 1; i <= NF; i++) {
        field = tolower(trim($i))
        if (field == "login") {
          login_col = i
        } else if (field == "roles") {
          roles_col = i
        }
      }

      if (!login_col || !roles_col) {
        fail(path ": missing required column(s): login, roles")
      }
      next
    }

    {
      login = trim($login_col)
      roles = trim($roles_col)

      if (login == "" && roles == "") {
        next
      }
      if (login == "") {
        fail(path ":" NR ": login must not be empty")
      }
      if (login in seen) {
        fail(path ":" NR ": duplicate login: " login)
      }
      if (roles == "" || roles !~ /[^|;[:space:]]/) {
        fail(path ":" NR ": roles must contain at least one role name or UUID")
      }

      seen[login] = 1
      count++
      print login "\t" roles
    }

    END {
      if (failed) {
        exit 1
      }
      if (NR == 0) {
        fail(path ": missing CSV header")
      }
      if (count == 0) {
        fail(path ": no users to import")
      }
    }
  ' "${csv_file}"
}

roles_to_json() {
  local roles="$1"
  printf '%s' "${roles}" | jq -Rc '
    gsub(";"; "|")
    | split("|")
    | map(gsub("^[[:space:]]+|[[:space:]]+$"; ""))
    | map(select(length > 0))
  '
}

fetch_collection() {
  local resource="$1"
  local per_page=1000
  local page=1
  local total_pages=1
  local page_file

  TMP_DIR="$(mktemp -d)"

  while (( page <= total_pages )); do
    page_file="$(printf '%s/%s-page-%05d.json' "${TMP_DIR}" "${resource}" "${page}")"
    api_get "/api/v1/${resource}?page=${page}&perPage=${per_page}" > "${page_file}"

    if (( page == 1 )); then
      total_pages="$(jq -r '.pagination.totalPages // 1' "${page_file}")"
      if [[ ! "${total_pages}" =~ ^[0-9]+$ ]] || (( total_pages < 1 )); then
        total_pages=1
      fi
    fi

    page=$((page + 1))
  done

  jq -s '
    {
      data: (map(.data // []) | add // []),
      pagination: {
        page: 1,
        perPage: (.[0].pagination.perPage // 1000),
        total: (.[0].pagination.total // (map((.data // []) | length) | add // 0)),
        totalPages: (.[0].pagination.totalPages // length)
      }
    }
  ' "${TMP_DIR}/${resource}"-page-*.json

  rm -rf "${TMP_DIR}"
  TMP_DIR=""
}

find_user_by_login() {
  local login="$1"
  printf '%s' "${USERS_JSON}" | jq -c --arg login "${login}" '
    (.data // [])
    | map(select(.name == $login))
    | if length == 0 then null
      elif length == 1 then .[0]
      else error("multiple users named " + $login)
      end
  '
}

resolve_role_ids() {
  local requested_roles="$1"
  jq -nec --argjson requested "${requested_roles}" --argjson catalog "${ROLES_JSON}" '
    def is_uuid:
      test("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

    $requested
    | map(
        . as $role
        | if ($role | is_uuid) then
            $role
          else
            (($catalog.data // []) | map(select(.name == $role))) as $matches
            | if ($matches | length) == 1 then
                $matches[0].id
              elif ($matches | length) == 0 then
                error("role not found: " + $role)
              else
                error("role name is ambiguous: " + $role)
              end
          end
      )
    | unique
  '
}

generate_password() {
  openssl rand -hex 12
}

if [[ $# -ne 1 ]]; then
  usage >&2
  exit 1
fi

require_command curl
require_command awk
require_command jq
require_command mktemp
require_command openssl

CSV_FILE="$1"
if [[ ! -r "${CSV_FILE}" ]]; then
  echo "CSV file is not readable: ${CSV_FILE}" >&2
  exit 1
fi

BASE_URL="${GVM_GATEWAY_BASE_URL:-http://127.0.0.1:8080}"
USERNAME="${GVM_GATEWAY_USERNAME:-admin}"
PASSWORD="${GVM_GATEWAY_PASSWORD:-admin}"
SESSION_TOKEN=""
TMP_DIR=""

trap cleanup EXIT

CSV_USERS_FILE="$(mktemp)"
parse_csv_users "${CSV_FILE}" > "${CSV_USERS_FILE}"
SESSION_JSON="$(create_session)"
SESSION_TOKEN="$(printf '%s' "${SESSION_JSON}" | jq -er '.sessionToken')"
GMP_VERSION="$(printf '%s' "${SESSION_JSON}" | jq -r '.gmpVersion')"

USERS_JSON="$(fetch_collection users)"
ROLES_JSON="$(fetch_collection roles)"

created_count=0
updated_count=0

while IFS=$'\t' read -r LOGIN ROLE_NAMES; do
  REQUESTED_ROLES="$(roles_to_json "${ROLE_NAMES}")"
  ROLE_IDS="$(resolve_role_ids "${REQUESTED_ROLES}")"
  EXISTING_USER="$(find_user_by_login "${LOGIN}")"

  if [[ "${EXISTING_USER}" == "null" ]]; then
    GENERATED_PASSWORD="$(generate_password)"
    BODY="$(
      jq -n \
        --arg name "${LOGIN}" \
        --arg password "${GENERATED_PASSWORD}" \
        --argjson roles "${ROLE_IDS}" \
        '{
          name: $name,
          password: $password,
          roles: $roles,
          authenticationType: "file"
        }'
    )"
    CREATED_JSON="$(api_post_json '/api/v1/users' "${BODY}")"
    CREATED_ID="$(printf '%s' "${CREATED_JSON}" | jq -er '.id')"
    created_count=$((created_count + 1))
    echo "created user ${LOGIN} (${CREATED_ID}) password=${GENERATED_PASSWORD}"
  else
    USER_ID="$(printf '%s' "${EXISTING_USER}" | jq -er '.id')"
    BODY="$(jq -n --argjson roles "${ROLE_IDS}" '{roles: $roles}')"
    api_put_json "/api/v1/users/${USER_ID}" "${BODY}" >/dev/null
    updated_count=$((updated_count + 1))
    echo "updated user ${LOGIN} (${USER_ID})"
  fi
done < "${CSV_USERS_FILE}"

cat <<EOF
user import complete
  gateway:          ${BASE_URL}
  gmp version:      ${GMP_VERSION}
  users created:    ${created_count}
  users updated:    ${updated_count}
EOF
