[package]
name = "gvm-gateway-gvmd"
description = "Minimal gvmd adapter for the GVM gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
gvm-client.workspace = true
gvm-connection.workspace = true
gvm-gateway-domain = { path = "../gvm-gateway-domain" }
gvm-gmp.workspace = true
tokio.workspace = true

[dev-dependencies]
gvm-mock-server.workspace = true
